from setuptools import setup, find_packages

setup(
    name='geneflow',
    version='0.8.0',    
    description='TFG',
    url='https://github.com/CasillasAlba',
    author='Alba Casillas Rodríguez',
    author_email='albacaro@correo.ugr.es',
    license='MIT',
    packages=find_packages(),
       install_requires=['biopython',
                        'colour',
                        'GEOparse',
                        'imbalanced-learn',
                        'imblearn',
                        'kaleido',
                        'lxml',
                        'matplotlib',
                        'numpy',
                        'pandas',
                        'plotly',
                        'pyquery',
                        'pywebview',
                        'requests',
                        'requests-html',
                        'rpy2',
                        'scikit-learn',
                        'scikit-image',
                        'scipy',
                        'seaborn',
                        'urllib3',
                        'w3lib',
                        'websockets',
                        'zipp',
                      ],
    classifiers=[
        'Development Status :: 1 - 0.2',
        'Intended Audience :: Science/Research',
        'License :: MIT',  
        'Operating System :: WINDOWS :: Linux :: Macintosh',
        'Programming Language :: Python :: 3.6',
    ],
)


